---
- name: dowload jenkins
  apt_key:
   url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
   state: present

- name: add repo
  apt_repository:
    repo: echttps://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list
    state: present
    
- name: update
  apt:
   update_cache: yes

- name: install jenkins
  apt: 
   name: jenkins
   state: present

