---
- name: dowload jenkins
  command: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -

- name: add key
  command: echo deb https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list

- name: update
  apt:
   update_cache: yes

- name: install jenkins
  apt: 
   name: jenkins
   state: present

   